export const GET_COMMENT_SAGA = "GET_COMMENT_SAGA";
export const GET_COMMENT = "GET_COMMENT";

export const CREATE_COMMENT_SAGA = "CREATE_COMMENT_SAGA";

export const EDIT_COMMENT_SAGA = "EDIT_COMMENT_SAGA";

export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";
