export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_FORM = "OPEN_FORM";
export const SET_SUBMIT_EDIT_PROJECT = "SET_SUBMIT_EDIT_PROJECT";
export const SET_SUBMIT_CREATE_TASK = "SET_SUBMIT_CREATE_TASK";
export const SET_SUBMIT_EDIT_USER = "SET_SUBMIT_EDIT_USER";
