export const GET_ALL_PRIORITY_SAGA = "GET_ALL_PRIORITY_SAGA";
export const GET_ALL_PRIORITY = "GET_ALL_PRIORITY";

export const GET_ALL_STATUS_TASK_SAGA = "GET_ALL_STATUS_TASK_SAGA";
export const GET_ALL_STATUS_TASK = "GET_ALL_STATUS_TASK";

export const GET_ALL_TASK_TYPE_SAGA = "GET_ALL_TASK_TYPE_SAGA";
export const GET_ALL_TASK_TYPE = "GET_ALL_TASK_TYPE";

export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";
export const DELETE_TASK_SAGA = "DELETE_TASK_SAGA";

export const GET_TASK_DETAIL_SAGA = "GET_TASK_DETAIL_SAGA";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL";

export const UPDATE_STATUS_TASK_SAGA = "UPDATE_STATUS_TASK_SAGA";

export const CHANGE_TASK_DETAIL_MODAL = "CHANGE_TASK_DETAIL_MODAL";
export const CHANGE_ASSIGNESS_TASK_MODAL = "CHANGE_ASSIGNESS_TASK_MODAL";
export const REMOVE_USER_TASK = "REMOVE_USER_TASK";

export const UPDATE_TASK_SAGA = "UPDATE_TASK_SAGA";
export const HANDLE_CHANGE_POST_API_SAGA = "HANDLE_CHANGE_POST_API_SAGA";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
