export const USER_SIGN_IN_SAGA = "USER_SIGN_IN_SAGA";
export const US_LOGIN = "US_LOGIN";

export const GET_USERS_SAGA = "GET_USERS_SAGA";
export const GET_USER_SEARCH_SAGA = "GET_USER_SEARCH_SAGA";
export const GET_USERS = "GET_USERS";
export const GET_USERS_SEARCH = "GET_USERS_SEARCH";
export const CREATE_USER_SAGA = "CREATE_USER_SAGA";

export const ASSIGN_USER_PROJECT = "ASSIGN_USER_PROJECT";

export const REMOVE_USER_PROJECT_SAGA = "REMOVE_USER_PROJECT_SAGA";

export const GET_USERS_BY_PROJECT_SAGA = "GET_USERS_BY_PROJECT_SAGA";
export const GET_USERS_BY_PROJECT = "GET_USERS_BY_PROJECT";

export const USER_SIGN_UP_SAGA = "USER_SIGN_UP_SAGA";

export const EDIT_USER_SAGA = "EDIT_USER_SAGA";
export const EDIT_USER = "EDIT_USER";

export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const TOGGLE_PASSWORDS = "TOGGLE_PASSWORDS";
